import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ChatContextProvider from "./useContext/chatContex";
import { MessageProvider } from "./useContext/message-context";
import { Providers } from "./Providers";
import CoinContextProvider from "./useContext/coinContext";
import { AgentLoadProvider } from "./useContext/agent-load-context";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-[#0A0F1E]`}
      >
        <Providers>
          <AgentLoadProvider>
            <MessageProvider>
              <ChatContextProvider>
                            <CoinContextProvider>{children}</CoinContextProvider>

              </ChatContextProvider>
            </MessageProvider>
          </AgentLoadProvider>
        </Providers>
      </body>
    </html>
  );
}
